### ISSUE TITLE
Почему Dedalus, а не Daedalus?

### ISSUE THREAD

**Issue by bamx23** [LuckyGeck/dedalus#1]
Любопытно, почему выбрано такое имя. Это баг или фича?
https://en.wikipedia.org/wiki/Daedalus

**Comment by LuckyGeck** [comment]
Не скажу, баг это или фича - просто решил, что так звучит лучше. Да и такой вариант имени Дедал, судя по выдаче гугла, так же существует.
Версия с daedalus была изначально, но название это как-то связано с едой и ее доеданием, что мне показалось не очень уместным =)
